"colorscheme twilight
setlocal spell
setlocal spelllang=en_us
setlocal softtabstop=2
setlocal shiftwidth=2
setlocal colorcolumn=
let maplocalleader=","
setlocal nocursorline
"setlocal background=light
